apiVersion: experimental.kontinue.io/v1
kind: CompletionRule
metadata:
  name: kpack-build
spec:
  resource:
    kind: Build
    apiVersion: build.pivotal.io/v1alpha1
  failed:
    - condition:
        type: "Failed"
        status: "True"
  succeeded:
    - condition:
        type: "Succeeded"
        status: "True"

---

apiVersion: experimental.kontinue.io/v1
kind: CompletionRule
metadata:
  name: pipeline-run
spec:
  resource:
    kind: PipelineRun
    apiVersion: tekton.dev/v1beta1
  failed:
    - condition:
        type: "Succeeded"
        status: "False"
  succeeded:
    - condition:
        type: "Succeeded"
        status: "True"

---

apiVersion: experimental.kontinue.io/v1
kind: CompletionRule
metadata:
  name: task-run
spec:
  resource:
    kind: TaskRun
    apiVersion: tekton.dev/v1beta1
  failed:
    - condition:
        type: "Succeeded"
        status: "False"
  succeeded:
    - condition:
        type: "Succeeded"
        status: "True"

---

apiVersion: experimental.kontinue.io/v1
kind: CompletionRule
metadata:
  name: deployment
spec:
  resource:
    kind: Deployment
    apiVersion: apps/v1
  failed:
    - after: 5m
  succeeded:
    - condition:
        type: "Available"
        status: "True"
